name: Sourcegraph
on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  scip:
    runs-on: ubuntu-latest
    name: "generate-scip"
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1
        with:
          jvm: "temurin:17"
          apps: scip-java

      - name: Generate SCIP File
        run: scip-java index --build-tool=sbt

      - name: Install src
        run: yarn global add @sourcegraph/src

      - name: Upload SCIP file
        run: src code-intel upload -github-token $GITHUB_TOKEN
        if: github.head_ref == 'master' 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
